@startuml

skinparam classAttributeIconSize 0

class Main {
  -String  mensage
  +toString ()
}
class ConversorMoneda {
  -float cantidad
  -String moneda1
  -String moneda2
  -String moneda3
  -String moneda4
  -String moneda5
  -double conversion
  +ConversorMoneda()
  +ConversorMoneda(float cantidad ...
  ..)
  +getCantidad()
  +setCantidad()
  +getmoneda1()
  +setmoneda1()
  +getmoneda2()
  +setmoneda2()
  +getmoneda3()
  +setmoneda3()
  +getmoneda4()
  +setmoneda4()
  +getmoneda5()
  +setmoneda5()
  toString()

}

Main <|---ConversorMoneda

@enduml